#!/usr/bin/env bash

################
# BASH Aliases #
################
alias ...='cd ../../'
alias ..='cd ../'
alias dd='sudo dd'
alias diff='colordiff'
alias grep='grep --color=always'
alias ll='ls -lAh'
alias ls='ls --color=always'
alias lsa='ls -A'
alias lt='ls -lAtrh'
alias mount='sudo mount'
alias reboot='sudo reboot'
alias sbp='. ${HOME}/.bash_profile'
alias shutdown='sudo shutdown'
alias sudo='sudo ' # Enable aliases to be sudo’ed
alias umount='sudo umount'

####################
# Function Aliases #
####################
alias duh='duDir'
alias ip='showIPS'

###################
# Utility Aliases #
###################
alias _du='diskutil'
alias _dul='diskutil list'
alias cleanup='find . -type f -name "*.DS_Store" -ls -delete'
alias czkawka='PATH="$HOME/.local/bin:$PATH" czkawka_krokiet'
alias flush='dscacheutil -flushcache &>/dev/null && killall -HUP mDNSResponder &>/dev/null'
alias getpaths='/usr/libexec/path_helper -s'
alias hosts='sudo vim /etc/hosts'
alias icloud="cd ${HOME}/Library/Mobile\ Documents/com~apple~CloudDocs"
alias map='xargs -n1'
alias ncdu='ncdu --color dark --enable-refresh --confirm-delete --delete-command trash'
alias pb='printf "%s" "$(cat)"|pbcopy'
alias pip3='python3 -m pip'
alias rsync='rsync --progress -v -h'
alias tdate='date "+%Y%m%d"'
alias vi='vim'
alias wolpc='osascript -e "tell application \"BetterTouchTool\" to trigger_named \"Launch Windows App\""'

####################
# Settings Aliases #
####################
alias _bt-off='sudo nvram bluetoothHostControllerSwitchBehavior=always'
alias _bt-on='sudo nvram -d bluetoothHostControllerSwitchBehavior'
alias hidedesktop='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias hideF='defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder'
alias noquar='xattr -d com.apple.quarantine'
alias pumpitup='osascript -e  "set volume output volume 100"'
alias showdesktop='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'
alias showf='defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder'
alias stfu='osascript -e "set volume output muted true"'

###############
# Git Aliases #
###############
alias gb='git branch'
alias gc='git checkout'
alias gd='git diff'
alias gp='git pull'
alias gs='git status'
alias gpm='git pull origin main'
alias gcm='git switch main'
alias gcb='git switch bbrinkerhoff 2>/dev/null || git switch -c bbrinkerhoff'
alias gbd='pruneGitBranches'
alias gbD='pruneGitBranches all'
alias gnb='git switch main && git switch -c'
alias mkpr='makePullRequest'

###################
# Vagrant Aliases #
###################
alias v='vagrant'
alias vb='vagrant box'
alias vgs='vagrant global-status'
alias vrm='vagrant destroy -f'
alias vs='vagrantSSH'
alias vu='vagrant up'

###################
# Chezmoi Aliases #
###################
alias cm='chezmoi'
alias cma='chezmoi apply -v'
alias cmr='chezmoi re-add'
alias cmd='chezmoi diff'
alias cmcd='cd $(chezmoi source-path)'
