#!/usr/bin/env bash

################
# BASH Aliases #
################
alias ...='cd ../../'
alias ..='cd ../'
alias dd='sudo dd'
alias diff='colordiff'
alias grep='grep --color=always'
alias ll='ls -lAh'
alias ls='ls --color=always'
alias lsa='ls -A'
alias lt='ls -lAtrh'
alias mount='sudo mount'
alias reboot='sudo reboot'
alias sbp='. ${HOME}/.bash_profile'
alias shutdown='sudo shutdown'
alias sudo='sudo ' # Enable aliases to be sudo’ed
alias umount='sudo umount'

###################
# Chezmoi Aliases #
###################
alias cm='chezmoi'
alias cma='chezmoi apply -v'
alias cmr='chezmoi re-add'
alias cmd='chezmoi diff'
alias cmcd='cd $(chezmoi source-path)'
