#!/usr/bin/env bash
###########################
## Misc profile commands ##
###########################
shopt -s checkwinsize
shopt -s histappend

###########################
## Text Output Functions ##
###########################
_txt() { tput -T xterm-256color $@; } # set text attributes
_fg() { _txt setaf ${1}; }            # set the foreground text color
_bg() { _txt setab ${1}; }            # set the background text color
_join() {
  local IFS=${1}
  printf "${*:2}"
} # join arguments with ${1} delimiter
_info() {
  local IFS=$'\n'
  printf "${G} *  INFO${RS}: %s\n" "$*"
} # print 'INFO' text to stdout
_warn() {
  local IFS=$'\n'
  printf "${Y} *  WARN${RS}: %s\n" "$*"
} # print 'WARN' text to stdout
_error() {
  local IFS=$'\n'
  printf "${R} * ERROR${RS}: %s\n" "$*" 1>&2
} # print 'ERROR' text to stderr
_erase() { for ((i = 1; i <= ${1:-1}; i++)); do
  tput cuu1
  tput el
done; } # move cursor up a line and erase x times
_print() {
  local IFS=$'\n' c
  c="${1:0:2}" c="${c^^}" c="${!c}" # print arguments with an optional color arg +
  shift 0${c:+1}
  printf "$c%b\n" "$*${RS}"
} #  to stdout separated by a newline
######################
## Text Output Vars ##
######################
export BLD=$(_txt bold)
export DIM=$(_txt dim)
export UL=$(_txt smul)
export ITL=$(_txt sitm)
export RS=$(_txt sgr0)
export RESET="${RS}"
export R=$(_fg 9)
export RED="${RED}"
export G=$(_fg 10)
export GREEN="${G}"
export B=$(_fg 12)
export BLUE="${B}"
export Y=$(_fg 11)
export YELLOW="${Y}"
