#!/usr/bin/env bash

##################################
## System Path variable exports ##
##################################
# Get Brew 'gnubin'/'gnuman' PATHs to prefer GNU versions of commands
[ -n ${BREW_PREFIX:+x} ] && BREW_PREFIX=$(brew --prefix)
BREW_GNUPATHS=($(find "${BREW_PREFIX}/Cellar" -mindepth 4 -maxdepth 4 -type d -path '*/libexec/gnubin' 2>/dev/null))
BREW_MANPATHS=($(find "${BREW_PREFIX}/Cellar" -mindepth 4 -maxdepth 4 -type d -path '*/libexec/gnuman' 2>/dev/null))

IFS=':'
PATH="${BREW_GNUPATHS[*]}:${PATH}"
MANPATH="${BREW_MANPATHS[*]}:${MANPATH}"
unset IFS
PATH+=":/usr/local/sbin:/usr/local/bin"
PATH+=":/Applications/iTerm.app/Contents/Resources/utilities"
PATH+=":/Applications/Sublime Text.app/Contents/SharedSupport/bin"
export PATH MANPATH
